definitions:
  web.Response:
    properties:
      code:
        type: string
      data: {}
      error:
        type: string
    type: object
info:
  contact:
    name: API Support
    url: https://hola.com
  description: This Api Handle MELI Product
  license:
    name: Apache 2.0
    url: https://github.com/
  termsOfService: hola
  title: MELI Bootcamp API
  version: "1.0"
paths:
  /api/v1/users:
    get:
      consumes:
      - application/json
      description: get users
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.Response'
      summary: List users
      tags:
      - Users
swagger: "2.0"
